CREATE DATABASE cafechronicles;
USE cafechronicles;

CREATE TABLE cafes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    location VARCHAR(255) NOT NULL
);

CREATE TABLE login(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);