CREATE DATABASE cafechronicles;
USE cafechronicles;

CREATE TABLE cafes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cafeName VARCHAR(255) UNIQUE NOT NULL,
    cafeLocation VARCHAR(255) NOT NULL
);

CREATE TABLE users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);